name: Build IG

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update the image to the latest publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o ./input-cache/publisher.jar --create-dirs

      - name: Run the IG publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: java -jar ./input-cache/publisher.jar publisher -ig .

      - name: Load deploy SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}

      - name: Deploy to test server
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.TEST_SSH_HOST }}" >> ~/.ssh/known_hosts
          rsync -avz --no-perms --no-owner --no-group \
            -e "ssh -o StrictHostKeyChecking=yes" \
            ./output/ "${{ secrets.TEST_SSH_USER }}@${{ secrets.TEST_SSH_HOST }}:${{ secrets.TEST_DEPLOY_PATH }}/"
